// <auto-generated />
namespace DiplomaProjectManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddTeamNameProperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTeamNameProperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201803172220297_AddTeamNameProperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
